using System;
using System.Text.Json;
using Festival.Core;
public static class SimulationTests {
 static int sequence;
 static GameCommand C(string kind,string item="",string target="",int amount=0){return new GameCommand{Id="test_"+(++sequence),Kind=kind,ItemId=item,TargetId=target,Amount=amount};}
 static void Assert(bool condition,string why){if(!condition)throw new Exception(why);}
 static FestivalSimulation Game(){var s=new FestivalSimulation();var a=s.AddPlayer("a","A");var b=s.AddPlayer("b","B");a.X=b.X=0;a.Z=b.Z=19;s.Execute("a",C("Ready"));s.Execute("b",C("Ready"));Assert(s.Execute("a",C("Start")).Accepted,"start");s.Execute("a",C("MapReady"));s.Execute("b",C("MapReady"));Assert(s.State.Phase=="Playing","map ready");return s;}
 public static void Run(){
  var capacity=new FestivalSimulation();for(int i=0;i<8;i++)capacity.AddPlayer(i.ToString(),"P");bool denied=false;try{capacity.AddPlayer("9","P");}catch(InvalidOperationException){denied=true;}Assert(denied&&capacity.State.Players.Count==8,"capacity");
  var shop=new FestivalSimulation();var p=shop.AddPlayer("a","A");var shelf=Catalog.ShopPoint(true,shop.State.VendorOffers.IndexOf("stock_lsd"));p.X=shelf.X;p.Z=shelf.Z;Assert(shop.Execute("a",C("HoldOffer","stock_lsd")).Accepted,"hold shelf copy");Assert(!shop.Execute("a",C("HoldOffer","stock_mushrooms")).Accepted,"one held item");p.X=0;p.Z=7;var buy=C("Buy","stock_lsd",amount:1);Assert(shop.Execute("a",buy).Accepted,"buy");shop.Execute("a",buy);Assert(p.Cash==15&&p.Inventory[0].Count==1,"buy exactly once");Assert(!shop.Execute("a",C("Buy","stock_lsd",amount:-1)).Accepted,"negative buy");
  var spoonShelf=Catalog.ShopPoint(true,shop.State.VendorOffers.IndexOf("little_spoon"));p.X=spoonShelf.X;p.Z=spoonShelf.Z;Assert(shop.Execute("a",C("HoldOffer","little_spoon")).Accepted,"spoon pickup");p.X=0;p.Z=7;Assert(shop.Execute("a",C("Buy","little_spoon",amount:1)).Accepted,"spoon purchase");Assert(p.EquippedItemId!="little_spoon"&&!shop.Execute("a",C("Equip","little_spoon")).Accepted,"spoon remains passive necklace");
  Assert(!shop.Execute("a",C("EnterCamp",target:"car_1")).Accepted,"camp entry checks distance");p.X=-14;p.Z=-15;Assert(shop.Execute("a",C("EnterCamp",target:"car_1")).Accepted&&p.CampVisitId=="car_1","enter car");float outsideX=p.X;Assert(shop.TryMove("a",p.CampInteriorX+.2f,p.CampInteriorZ,0,.1)&&p.X==outsideX,"walk inside without moving exterior avatar");Assert(!shop.TryMove("a",39,-12,0,.1),"interior walls constrain movement");Assert(shop.Execute("a",C("CampAntic")).Accepted&&p.CampGag.Contains("horn"),"car antic");Assert(shop.Execute("a",C("ExitCamp")).Accepted&&p.CampVisitId=="","exit car");
  p.X=CampFeatures.DjX;p.Z=CampFeatures.DjZ;Assert(shop.Execute("a",C("ChooseCampTrack",amount:2)).Accepted&&shop.State.CampMusicTrack==2,"shared DJ selection");Assert(!shop.Execute("a",C("ChooseCampTrack",amount:9)).Accepted,"DJ rejects unknown track");
  var s=Game();p=s.Player("a");Assert(!s.TryMove("a",float.NaN,0,0,.1),"NaN movement");Assert(!s.TryMove("a",20,20,0,.1),"teleport");p.Inventory.Add(new ItemStack{ItemId="stock_lsd",Count=2});p.Inventory.Add(new ItemStack{ItemId="stock_mushrooms",Count=1});Assert(s.Execute("a",C("Consume","stock_lsd")).Accepted,"LSD");Assert(!s.Execute("a",C("Consume","stock_lsd")).Accepted&&p.Inventory[0].Count==1,"repeat effect retains stock");Assert(s.Execute("a",C("Consume","stock_mushrooms")).Accepted&&p.Effects.Count==2,"two effects");s.Tick(60);Assert(p.Effects.Count==0,"expiry");
  s=Game();p=s.Player("a");float start=p.X;Assert(s.TryMove("a",start+.59f,p.Z,0,.1),"sober stride accepted");p.X=start;p.Inventory.Add(new ItemStack{ItemId="stock_lsd",Count=1});Assert(s.Execute("a",C("Consume","stock_lsd")).Accepted,"take tabs");Assert(!s.TryMove("a",start+.59f,p.Z,0,.1),"impaired stride is host limited");Assert(Math.Abs(Intoxication.LateralDrift(p,1))>.01,"impaired direction wanders");
  s=Game();p=s.Player("a");var b=s.Player("b");p.X=b.X=0;p.Z=b.Z=-20;p.Inventory.Add(new ItemStack{ItemId="stock_lsd",Count=2});Assert(s.Execute("a",C("Transfer","stock_lsd","b",1)).Accepted,"offer");var offer=s.State.Transfers[0];Assert(b.Inventory.Count==0,"voluntary recipient");Assert(s.Execute("b",C("AcceptTransfer",target:offer.Id)).Accepted,"accept");Assert(b.Inventory[0].Count==1&&p.Inventory[0].Count==1,"handoff conserved");
  s=Game();p=s.Player("a");b=s.Player("b");b.Life="Detained";p.Cash=0;p.X=-28;p.Z=16;Assert(s.Execute("a",C("BeginRelease",target:"b")).Accepted,"free release");s.Tick(10.1);Assert(b.Life=="Alive"&&p.Cash==0,"broke pair release");
  s=Game();p=s.Player("a");b=s.Player("b");b.Life="Downed";b.DownedRemaining=.1;b.X=0;b.Z=-20;s.Tick(.2);Assert(b.Life=="Spirit"&&s.State.Drops.FindAll(x=>x.ItemId=="wristband").Count==1,"one death band");p.X=0;p.Z=-20;Assert(s.Execute("a",C("Pickup",target:s.State.Drops.Find(x=>x.ItemId=="wristband").Id)).Accepted,"band pickup");p.X=24;p.Z=-20;p.Cash=0;var revive=C("BeginRevival",target:"b");Assert(s.Execute("a",revive).Accepted,"free revival");s.Tick(10.1);s.Execute("a",revive);Assert(b.Life=="Alive"&&b.Health==40&&b.RevivalCount==1&&p.Wristbands.Count==0,"exactly one revival");
  s=Game();s.State.GateOpened=true;p=s.Player("a");p.X=s.State.FriendPosition.X;p.Z=s.State.FriendPosition.Z;Assert(s.Execute("a",C("FindFriend")).Accepted,"recruit");s.Tick(2.1);p.X=0;p.Z=-32;s.State.FriendPosition.X=0;s.State.FriendPosition.Z=-32;Assert(s.Execute("a",C("Extract")).Accepted,"extract");s.Tick(3.1);Assert(s.State.Result=="Success"&&p.HasCosmetic,"one win reward");Assert(s.Execute("a",C("Reset")).Accepted&&s.State.Phase=="CampReview"&&s.State.GrossSales==0&&s.Player("a").HasCosmetic,"return to camp review preserves cosmetic");
  Assert(!s.Execute("a",C("FinishReview")).Accepted,"review blocks shopping until votes");Assert(s.Execute("a",C("ReviewVote",amount:0)).Accepted,"host vote");Assert(!s.Execute("a",C("FinishReview")).Accepted,"wait for connected crew");Assert(s.Execute("b",C("ReviewVote",amount:2)).Accepted,"crew vote");Assert(!s.Execute("b",C("FinishReview")).Accepted,"only host opens shop");Assert(s.Execute("a",C("FinishReview")).Accepted&&s.State.Phase=="Shopping","review precedes next shop");
  s=Game();s.State.DurationSeconds=.2;s.Tick(.3);Assert(s.State.Result=="Time expired","deadline");
  s=Game();p=s.Player("a");var witness=s.State.Npcs[0];witness.X=p.X;witness.Z=p.Z+1;witness.Yaw=180;var nonWitness=s.State.Npcs[10];nonWitness.X=35;nonWitness.Z=35;
  Assert(s.Execute("a",C("Dance",target:witness.Id)).Accepted,"local dance starts");s.Tick(9);
  var localSuspicion=witness.Observers.Find(o=>o.PlayerId==p.Id);var remoteSuspicion=nonWitness.Observers.Find(o=>o.PlayerId==p.Id);
  Assert(localSuspicion!=null&&localSuspicion.Suspicion>0&&remoteSuspicion!=null&&remoteSuspicion.Suspicion==0,"suspicion is observer-local");
  s=Game();p=s.Player("a");s.State.Npcs.Clear();p.X=0;p.Z=0;var listener=new NpcState{Id="listener",X=0,Z=1,Yaw=180,CanTalk=true};listener.Observers.Add(new ObserverState{PlayerId=p.Id,Suspicion=40});s.State.Npcs.Add(listener);
  Assert(s.Execute("a",C("Conversation",target:listener.Id)).Accepted,"start NPC conversation");var talk=s.Interaction(p.InteractionId);Assert(!string.IsNullOrWhiteSpace(talk.DialogueText),"NPC responds with dialogue");
  foreach(var note in RhythmChart.Create(talk.ChartSeed,talk.NoteCount,talk.BeatSeconds).Notes)talk.Inputs.Add(new RhythmInput{Direction=note.Direction,TimeSeconds=note.TimeSeconds});
  s.Tick(10);Assert(p.LastRhythmScore>.99&&listener.Observers[0].Suspicion<40,"conversation improves local trust");
  p.Inventory.Add(new ItemStack{ItemId="confetti",Count=1});Assert(s.Execute("a",C("Use","confetti")).Accepted,"confetti works");
  Assert(p.Inventory.Find(x=>x.ItemId=="confetti")==null&&listener.DistractedUntil>s.State.SimulationSeconds,"item consumed and wook distracted");s.Tick(.1);Assert(listener.Mode=="Distracted","wook visibly changes mode");
  s=Game();p=s.Player("a");p.Inventory.Add(new ItemStack{ItemId="stock_lsd",Count=1});var npc=s.State.Npcs[0];npc.X=p.X;npc.Z=p.Z+1;npc.Yaw=180;var distant=s.State.Npcs[10];distant.X=35;distant.Z=35;var cop=s.State.Npcs.Find(n=>n.Kind=="Cop");cop.X=p.X;cop.Z=p.Z+2;cop.Yaw=180;Assert(s.Execute("a",C("StartSale","stock_lsd",npc.Id)).Accepted,"sale reserve");s.Tick(4.1);Assert(p.Life=="Detained"&&p.Inventory.Count==0&&s.State.GrossSales==0&&p.Cash==10,"bust precedes settlement");
  s=Game();p=s.Player("a");p.X=-28;p.Z=16;var quest=C("LostProperty");s.Execute("a",quest);s.Tick(5.1);s.Execute("a",quest);Assert(p.Cash==25&&s.State.GrossSales==0,"income distinct from sales");
  s=Game();p=s.Player("a");p.Inventory.Add(new ItemStack{ItemId="stock_lsd",Count=1});var consume=C("Consume","stock_lsd");Assert(s.Execute("a",consume).Accepted,"snapshot setup");s.Tick(1.25);
  var json=JsonSerializer.Serialize(s.State,new JsonSerializerOptions{IncludeFields=true});var saved=JsonSerializer.Deserialize<RoundState>(json,new JsonSerializerOptions{IncludeFields=true});
  var restored=new FestivalSimulation();restored.Restore(saved);double before=restored.State.ElapsedSeconds;int effectCount=restored.Player("a").Effects.Count;restored.Execute("a",consume);restored.Tick(.5);
  Assert(restored.Player("a").Effects.Count==effectCount&&restored.State.ElapsedSeconds>before&&restored.State.Commands.Exists(c=>c.Id==consume.Id),"snapshot continuity and dedupe");
 }
}
